project_name: 'RNAflow'
Genome_Version: "Lsat_Salinas_v11" # Lsat_Salinas_v8,Lsat_Salinas_v11
# short read raw-data
raw_data_path:
  - /data/jzhang/project/RNAFlow_Analysis_pipeline/00.raw_data
# short read samples info
sample_csv: /data/jzhang/project/RNAFlow_Analysis_pipeline/01.workflow/sample.csv
# workflow
workflow: /data/jzhang/project/RNAFlow_Analysis_pipeline/01.workflow
# RNAflow Output file
data_deliver: /data/jzhang/project/RNAFlow_Analysis_pipeline/02.data_deliver