project_name: 'HYXM-251215018'
Genome_Version: "GRCm39" # Lsat_Salinas_v8,Lsat_Salinas_v11,ITAG4.1,TAIR10.1,GRCm39,hg38
# short read raw-data
raw_data_path:
  - /data/jzhang/project/Temp/HYXM-251215018/00.raw_data/HYXM-251215018-SEQ/Fastq
# short read samples info
sample_csv: /data/jzhang/project/Temp/HYXM-251215018/01.workflow/sample.csv
paired_csv: /data/jzhang/project/Temp/HYXM-251215018/01.workflow/contrasts.csv
# workflow
workflow: /data/jzhang/project/Temp/HYXM-251215018/01.workflow
# RNAflow Output file
data_deliver: /data/jzhang/project/Temp/HYXM-251215018/02.data_deliver
# Fragment Library Types
Library_Types: fr-firststrand # fr-unstranded,fr-firststrand,fr-secondstrand
# wheather call variant for RNA-seq
call_variant: false
# Detech Noval Transcripts by stringtie
noval_Transcripts: false
# rmats
rmats: true