# softeware path
software:
  json_md5_verifier: /home/jzhang/pipeline/RNAFlow/src/src/md5/Compile_release/json_md5_verifier_x86_64/release/json_md5_verifier
  seq_preprocessor: /home/jzhang/pipeline/RNAFlow/src/src/md5/Compile_release/seq_preprocessor_x86_64/release/seq_preprocessor
# md5
raw_data:
  md5: 'md5.txt'
# software parameter
parameter:
  star_index:
    Lsat_Salinas_v11:
      index: /data/jzhang/reference/Lactuca_sativa_V11/STAR_Lactuca_sativa_V11_index/Lsat_Salinas_v11
      genome_fa: /data/jzhang/reference/Lactuca_sativa_V11/STAR_Lactuca_sativa_V11_index/Lsat_Salinas_v11.genome.fasta
      genome_gtf: /data/jzhang/reference/Lactuca_sativa_V11/STAR_Lactuca_sativa_V11_index/Lsat_Salinas_v11.genome.gtf
      genome_gff: /data/jzhang/reference/Lactuca_sativa_V11/STAR_Lactuca_sativa_V11_index/Lsat_Salinas_v11.genome.gff
      rsem_index: /data/jzhang/reference/Lactuca_sativa_V11/STAR_Lactuca_sativa_V11_index/RSEM_Lsat_Salinas_v11/Lsat_Salinas_v11
      ploidy: 2
    Lsat_Salinas_v8:
      index: /data/jzhang/reference/Lactuca_sativa_V8/STAR_Lactuca_sativa_V8_index/Lsat_Salinas_v8
      genome_fa: /data/jzhang/reference/Lactuca_sativa_V8/STAR_Lactuca_sativa_V8_index/Lactuca_sativa_V8A.fasta
      genome_gtf: /data/jzhang/reference/Lactuca_sativa_V8/STAR_Lactuca_sativa_V8_index/Lactuca_sativa_V8A.gtf
      genome_gff: /data/jzhang/reference/Lactuca_sativa_V8/STAR_Lactuca_sativa_V8_index/Lactuca_sativa_V8A.gff3
      rsem_index: /data/jzhang/reference/Lactuca_sativa_V8/STAR_Lactuca_sativa_V8_index/Lsat_Salinas_v8/Lsat_Salinas_v8
      ploidy: 2
    ITAG4.1:
      index: /data/jzhang/reference/S_lycopersicum/ITAG4.1_star_index
      genome_fa: /data/jzhang/reference/S_lycopersicum/S_lycopersicum_chromosomes.4.00.fa
      genome_gtf: /data/jzhang/reference/S_lycopersicum/ITAG4.1_gene_models.gtf
      genome_gff: /data/jzhang/reference/S_lycopersicum/ITAG4.1_gene_models.gff
      rsem_index: /data/jzhang/reference/S_lycopersicum/RSEM_ITAG4.1/ITAG4.1_index
      ploidy: 2
    TAIR10.1:
      index: /data/jzhang/reference/Arabidopsis_Thaliana/TAIR10.1_STAR_INDEX
      genome_fa: /data/jzhang/reference/Arabidopsis_Thaliana/TAIR10_chr_all.fas
      genome_gtf: /data/jzhang/reference/Arabidopsis_Thaliana/Araport11_GTF_genes_transposons.20241001.gtf
      genome_gff: /data/jzhang/reference/Arabidopsis_Thaliana/Araport11_GFF3_genes_transposons.20250813.gff
      rsem_index: /data/jzhang/reference/Arabidopsis_Thaliana/RSEM_TAIR10.1/TAIR10.1_index
      ploidy: 2
  threads:
    json_md5_verifier: 40
    fastqc: 1
    fastp: 8
    multiqc: 1
    fastq_screen: 10
    STAR_INDEX: 40
    STAR_MAPPING: 16
    samtools: 10
    samtools_flagstat: 10
    samtools_stats: 10
    qualimap: 10
    RSEM_INDEX: 20
    rsem-calculate: 20
    bamCoverage: 20
    stringtie: 16
    gatk: 1
  fastq_screen:
    run: true
    path: /home/jzhang/software/FastQ-Screen-0.16.0/fastq_screen
    conf: /home/jzhang/software/FastQ-Screen-0.16.0/fastq_screen.conf
    subset: 100000
    aligner: Bowtie2
  stringtie:
    min_length: 200      # 最小转录本长度 (植物lncRNA通常>200)
    min_cov: 5           # 最小覆盖度
    min_fpkm: 1.0        # 最小 FPKM (过滤低表达噪音)
  STAR:
    PL: ILUMINA
  qualimap:
    genome_gff: /data/jzhang/reference/Lactuca_sativa_V11/Lsat_Salinas_v11.genome.gff
    format: HTML
    mem: 20000M
  bamCoverage:
    binSize: 10
    smoothLength: 14
    normalizeUsing: RPKM # RPKM,CPM,BPM,RPGC
  gatk:
    filter:
      rna_seq:
        window_size: 35        # 窗口大小
        cluster_size: 3        # 集群数量阈值
        fs_threshold: 30.0     # Fisher Strand 阈值 (RNA建议30, DNA建议60)
        qd_threshold: 2.0      # Quality by Depth 阈值
  trim:
    length_required: 75
    quality_threshold: 25
    adapter_fasta: "../data/Universal_Adapter.fa"

can_use_genome_version:
  - Lsat_Salinas_v11
  - Lsat_Salinas_v8
  - ITAG4.1
  - TAIR10.1
# Other parameter
print_target: true
print_sample: false
log_level: INFO
bam_remove: true
convert_md5: 'link_dir'
r1_suffix: _R1.fq.g【z
r2_suffix: _R2.fq.gz
md5: MD5.txt