#!/usr/bin/env python3
"""
Project management services for RNAFlow MCP
"""

import csv
import yaml
from pathlib import Path
from typing import List, Dict, Any

from core.logger import logger
from core.config import CONFIG_DIR, EXAMPLES_DIR
from models.schemas import ProjectConfig


def list_supported_genomes() -> List[Dict[str, str]]:
    """List all supported genome versions in RNAFlow"""
    logger.info("=== 调用工具: list_supported_genomes ===")

    reference_yaml = CONFIG_DIR / "reference.yaml"
    if not reference_yaml.exists():
        error_msg = "reference.yaml not found"
        logger.error(error_msg)
        return [{"error": error_msg}]

    logger.info(f"读取配置文件: {reference_yaml}")
    with open(reference_yaml, "r", encoding="utf-8") as f:
        ref_config = yaml.safe_load(f)

    genomes = []
    source = "unknown"

    if "mcp_genome_version" in ref_config and ref_config["mcp_genome_version"]:
        source = "mcp_genome_version"
        for genome_name, genome_info in ref_config["mcp_genome_version"].items():
            genomes.append(
                {
                    "name": genome_info.get("name", genome_name),
                    "description": genome_info.get(
                        "description", f"Reference genome: {genome_name}"
                    ),
                }
            )
    elif "STAR_index" in ref_config:
        source = "STAR_index"
        for genome_name, genome_info in ref_config["STAR_index"].items():
            genomes.append(
                {"name": genome_name, "description": f"Reference genome: {genome_name}"}
            )

    logger.info(f"从 {source} 读取到 {len(genomes)} 个基因组版本")
    for genome in genomes:
        logger.debug(f"  - {genome['name']}: {genome['description']}")

    logger.info("=== 工具完成: list_supported_genomes ===")
    return genomes


def get_config_template(template_type: str = "standard") -> str:
    """Get a complete RNAFlow configuration template"""
    template_files = {
        "complete": EXAMPLES_DIR / "config_complete.yaml",
        "standard": EXAMPLES_DIR / "config_standard_deg.yaml",
        "qc_only": EXAMPLES_DIR / "config_qc_only.yaml",
    }
    template_file = template_files.get(template_type, template_files["standard"])

    if not template_file.exists():
        return f"Error: Template {template_type} not found at {template_file}"

    with open(template_file, "r", encoding="utf-8") as f:
        return f.read()


def create_project_structure(project_root: str) -> Dict[str, Any]:
    """Create standard RNAFlow project directory structure"""
    logger.info("=== 调用工具: create_project_structure ===")
    logger.info(f"项目根目录: {project_root}")

    try:
        root_path = Path(project_root).resolve()
        dirs = {
            "raw_data": root_path / "00.raw_data",
            "workflow": root_path / "01.workflow",
            "data_deliver": root_path / "02.data_deliver",
        }

        created_dirs = []
        for dir_name, dir_path in dirs.items():
            if not dir_path.exists():
                dir_path.mkdir(parents=True, exist_ok=True)
                created_dirs.append(str(dir_path))
                logger.info(f"创建目录: {dir_path}")
            else:
                logger.info(f"目录已存在: {dir_path}")

        result = {
            "success": True,
            "project_root": str(root_path),
            "directories": {k: str(v) for k, v in dirs.items()},
            "created": created_dirs,
            "message": "Project structure created successfully"
            if created_dirs
            else "Project structure already exists",
        }

        logger.info(f"项目结构创建完成: {result}")
        logger.info("=== 工具完成: create_project_structure ===")
        return result

    except Exception as e:
        logger.error(f"创建项目结构失败: {str(e)}", exc_info=True)
        logger.info("=== 工具完成: create_project_structure (失败) ===")
        return {"success": False, "error": str(e)}


def generate_config_file(config: ProjectConfig, output_path: str) -> str:
    """Generate RNAFlow config.yaml using ProjectConfig model"""
    try:
        out_path = Path(output_path).resolve()
        out_path.parent.mkdir(parents=True, exist_ok=True)
        config_dict = config.model_dump()
        config_dict = {k: v for k, v in config_dict.items() if v is not None}

        header = f"""# RNAFlow Analysis Configuration
# Generated by RNAFlow MCP Server
# Project: {config.project_name}
# Genome: {config.Genome_Version}
# Species: {config.species}

"""

        with open(out_path, "w", encoding="utf-8") as f:
            f.write(header)
            yaml.dump(config_dict, f, default_flow_style=False, sort_keys=False)

        logger.info(f"成功生成配置文件: {out_path}")
        return f"Successfully generated config file at {out_path}"
    except Exception as e:
        logger.error(f"生成配置文件失败: {str(e)}", exc_info=True)
        return f"Error generating config file: {str(e)}"


def create_sample_csv(sample_data: List[Dict[str, str]], output_path: str) -> str:
    """Create samples.csv file"""
    try:
        out_path = Path(output_path).resolve()
        out_path.parent.mkdir(parents=True, exist_ok=True)

        with open(out_path, "w", newline="", encoding="utf-8") as csvfile:
            fieldnames = ["sample", "sample_name", "group"]
            writer = csv.DictWriter(
                csvfile, fieldnames=fieldnames, extrasaction="ignore"
            )
            writer.writeheader()
            for sample in sample_data:
                safe_sample = {key: sample.get(key, "unknown") for key in fieldnames}
                writer.writerow(safe_sample)
        return f"Successfully created samples.csv at {out_path}"
    except Exception as e:
        return f"Error creating samples.csv: {str(e)}"


def create_contrasts_csv(contrasts: List[Dict[str, str]], output_path: str) -> str:
    """Create contrasts.csv file"""
    try:
        out_path = Path(output_path).resolve()
        out_path.parent.mkdir(parents=True, exist_ok=True)

        with open(out_path, "w", newline="", encoding="utf-8") as csvfile:
            fieldnames = ["contrast", "treatment"]
            writer = csv.DictWriter(
                csvfile, fieldnames=fieldnames, extrasaction="ignore"
            )
            writer.writeheader()
            for contrast in contrasts:
                safe_contrast = {
                    key: contrast.get(key, "unknown") for key in fieldnames
                }
                writer.writerow(safe_contrast)
        return f"Successfully created contrasts.csv at {out_path}"
    except Exception as e:
        return f"Error creating contrasts.csv: {str(e)}"


def validate_config(config_path: str) -> Dict[str, Any]:
    """Validate RNAFlow configuration file"""
    config_file = Path(config_path).resolve()
    if not config_file.exists():
        return {"valid": False, "errors": ["Configuration file not found"]}

    try:
        with open(config_file, "r", encoding="utf-8") as f:
            config = yaml.safe_load(f)

        errors = []
        warnings = []
        required_fields = [
            "project_name",
            "Genome_Version",
            "species",
            "raw_data_path",
            "sample_csv",
            "paired_csv",
            "workflow",
            "data_deliver",
        ]
        for field in required_fields:
            if field not in config:
                errors.append(f"Missing required field: {field}")

        recommended_fields = [
            "client",
            "execution_mode",
            "Library_Types",
            "only_qc",
            "deg",
            "report",
        ]
        for field in recommended_fields:
            if field not in config:
                warnings.append(f"Missing recommended field: {field} (using defaults)")

        return {
            "valid": len(errors) == 0,
            "errors": errors,
            "warnings": warnings,
            "config": config if len(errors) == 0 else None,
        }
    except Exception as e:
        return {"valid": False, "errors": [str(e)]}


def get_project_structure() -> Dict[str, Any]:
    """Get standard RNAFlow project structure"""
    return {
        "directories": [
            "Project_Root/00.raw_data/        - Raw FASTQ files directory",
            "Project_Root/01.workflow/        - Workflow directory",
            "Project_Root/02.data_deliver/    - Output directory",
        ],
        "files": [
            "Project_Root/01.workflow/config.yaml      - Main configuration",
            "Project_Root/01.workflow/samples.csv     - Sample metadata",
            "Project_Root/01.workflow/contrasts.csv   - Contrast definitions",
        ],
        "description": "Standard project structure for RNAFlow analysis.",
        "quick_start": "1. Create structure\n2. Place FASTQ files\n3. Create CSV files\n4. Run analysis",
    }


def setup_complete_project(
    project_root: str,
    project_name: str,
    genome_version: str,
    species: str,
    analysis_mode: str = "standard",
    client: str = "Research_Lab",
    library_types: str = "fr-firststrand",
) -> Dict[str, Any]:
    """One-stop setup for complete RNAFlow project"""
    logger.info("=== 调用工具: setup_complete_project ===")
    logger.info(f"项目根目录: {project_root}")

    try:
        root_path = Path(project_root).resolve()
        struct_result = create_project_structure(str(root_path))
        if not struct_result.get("success", False):
            return struct_result

        mode_settings = {
            "complete": {
                "only_qc": False,
                "deg": True,
                "call_variant": True,
                "detect_novel_transcripts": True,
                "rmats": True,
                "fastq_screen": True,
                "report": True,
            },
            "standard": {
                "only_qc": False,
                "deg": True,
                "call_variant": False,
                "detect_novel_transcripts": False,
                "rmats": False,
                "fastq_screen": True,
                "report": True,
            },
            "qc_only": {
                "only_qc": True,
                "deg": False,
                "call_variant": False,
                "detect_novel_transcripts": False,
                "rmats": False,
                "fastq_screen": True,
                "report": True,
            },
        }
        settings = mode_settings.get(analysis_mode, mode_settings["standard"])

        workflow_dir = root_path / "01.workflow"
        raw_data_dir = root_path / "00.raw_data"
        data_deliver_dir = root_path / "02.data_deliver"
        config_path = workflow_dir / "config.yaml"
        samples_csv_path = workflow_dir / "samples.csv"
        contrasts_csv_path = workflow_dir / "contrasts.csv"

        config = ProjectConfig(
            project_name=project_name,
            Genome_Version=genome_version,
            species=species,
            client=client,
            raw_data_path=[str(raw_data_dir)],
            sample_csv=str(samples_csv_path),
            paired_csv=str(contrasts_csv_path),
            workflow=str(workflow_dir),
            data_deliver=str(data_deliver_dir),
            execution_mode="local",
            Library_Types=library_types,
            **settings,
        )

        config_result = generate_config_file(config, str(config_path))
        if "Error" in config_result:
            return {"success": False, "error": config_result}

        with open(samples_csv_path, "w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            writer.writerow(["sample", "sample_name", "group"])
            writer.writerow(
                ["example_sample_R1.fastq.gz", "ExampleSample_1", "Control"]
            )

        with open(contrasts_csv_path, "w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            writer.writerow(["Control", "Treat"])
            writer.writerow(["Control", "Treatment"])

        result = {
            "success": True,
            "project_root": str(root_path),
            "project_name": project_name,
            "analysis_mode": analysis_mode,
            "files": {
                "config": str(config_path),
                "samples_csv": str(samples_csv_path),
                "contrasts_csv": str(contrasts_csv_path),
            },
            "directories": {
                "raw_data": str(raw_data_dir),
                "workflow": str(workflow_dir),
                "data_deliver": str(data_deliver_dir),
            },
            "next_steps": [
                "1. Place FASTQ files in 00.raw_data/",
                "2. Edit samples.csv",
                "3. Edit contrasts.csv",
                "4. Review config.yaml",
                "5. Run analysis",
            ],
        }

        logger.info(f"项目设置完成: {result}")
        logger.info("=== 工具完成: setup_complete_project ===")
        return result

    except Exception as e:
        logger.error(f"项目设置失败: {str(e)}", exc_info=True)
        return {"success": False, "error": str(e)}


def run_simple_qc_analysis(
    project_root: str,
    genome_version: str,
    species: str,
    project_name: str = None,
) -> Dict[str, Any]:
    """Simple one-click QC analysis"""
    logger.info("=== 调用工具: run_simple_qc_analysis ===")
    logger.info(f"项目根目录: {project_root}")

    try:
        root_path = Path(project_root).resolve()
        if not project_name:
            project_name = root_path.name

        setup_result = setup_complete_project(
            project_root=str(root_path),
            project_name=project_name,
            genome_version=genome_version,
            species=species,
            analysis_mode="qc_only",
            client="Research_Lab",
            library_types="fr-firststrand",
        )

        if not setup_result.get("success", False):
            return setup_result

        raw_data_dir = root_path / "00.raw_data"
        fastq_files = []
        if raw_data_dir.exists():
            fastq_files = list(raw_data_dir.glob("*.fastq.gz")) + list(
                raw_data_dir.glob("*.fq.gz")
            )
            fastq_files += list(raw_data_dir.glob("*.fastq")) + list(
                raw_data_dir.glob("*.fq")
            )

        setup_result["fastq_files_found"] = len(fastq_files)
        setup_result["fastq_files"] = [str(f.name) for f in fastq_files[:10]]

        if fastq_files:
            setup_result["next_steps"] = [
                "✅ FASTQ files detected!",
                "1. Edit samples.csv",
                "2. Edit contrasts.csv",
                "3. Review config.yaml",
                "4. Run analysis",
            ]
        else:
            setup_result["next_steps"] = [
                "⚠️ No FASTQ files found",
                "Please place FASTQ files in 00.raw_data/",
            ]

        logger.info(f"简单QC分析设置完成: {setup_result}")
        logger.info("=== 工具完成: run_simple_qc_analysis ===")
        return setup_result

    except Exception as e:
        logger.error(f"简单QC分析设置失败: {str(e)}", exc_info=True)
        return {"success": False, "error": str(e)}
