#!/usr/bin/snakemake
# -*- coding: utf-8 -*-
"""
RNAFlow Pipeline - RSEM Gene and Isoform Quantification Module

This module handles transcript-level quantification using RSEM (RNA-Seq by Expectation-Maximization),
which provides accurate estimation of gene and isoform expression levels from RNA-seq data.

Key Components:
- RSEM: Main quantification rule that processes transcriptome-aligned BAM files
- rsem_multiqc: Quality control aggregation for RSEM results
- merge_rsem: Merges individual sample results into comprehensive expression matrices
- ultimate: Additional quality control and validation of quantification results

RSEM uses an expectation-maximization algorithm to resolve ambiguously mapped reads
and provides expression estimates in multiple formats including TPM (Transcripts Per Million),
FPKM (Fragments Per Kilobase of transcript per Million mapped reads), and raw counts.

Note: The build_rsem_index rule is currently commented out, assuming pre-built indexes
are available in the reference configuration.
"""

# rule build_rsem_index:
#    input:
#        genome_fa = config['STAR_index'][config['Genome_Version']]['genome_fa'],
#        genome_gtf = config['STAR_index'][config['Genome_Version']]['genome_gtf']
#    output:
#        chrlist = config['STAR_index'][config['Genome_Version']]['rsem_index'] + '.ti',
#        grp = config['STAR_index'][config['Genome_Version']]['rsem_index'] + '.seq',
#       idx_fa = config['STAR_index'][config['Genome_Version']]['rsem_index'] + '.transcripts.fa',
#    conda:
#        workflow.source_path("../envs/rsem.yaml"),
#    log:
#        "logs/02.mapping/rsem_index.log"
#    message:
#        "Building rsem index for {input.genome_gtf}"
#    params:
#        rsem_index_dir = config['STAR_index'][config['Genome_Version']]['rsem_index_dir'],
#        rsem_index = config['STAR_index'][config['Genome_Version']]['rsem_index'],
#    benchmark:
#        "benchmarks/rsem_index_benchmark.txt"
#    threads:
#        config['parameter']['threads']['RSEM_INDEX']
#    shell:
#        """
#        mkdir -p {params.rsem_index_dir} &&
#        rsem-prepare-reference --gtf {input.genome_gtf} \
#                       --star \
#                       -p {threads} \
#                       {input.genome_fa} \
#                       {params.rsem_index}  &>{log}
#        """

rule RSEM:
    """
    Perform gene and isoform expression quantification using RSEM.

    This rule takes the transcriptome-aligned BAM files generated by STAR's
    --quantMode TranscriptomeSAM option and estimates expression levels using
    RSEM's expectation-maximization algorithm. RSEM accounts for:
    - Ambiguously mapped reads (reads that map to multiple transcripts)
    - Transcript length bias
    - Sequencing depth differences

    The rule outputs comprehensive results including:
    - Gene-level expression (.genes.results)
    - Isoform-level expression (.isoforms.results)
    - Statistical files for quality assessment (.cnt, .model, .theta)

    Key parameters:
    - --estimate-rspd: Estimates read start position distribution
    - --calc-pme: Calculates posterior mean and variance
    - --seed: Ensures reproducible results
    """
    input:
        chrlist = config['STAR_index'][config['Genome_Version']]['rsem_index'] + '.ti',
        grp = config['STAR_index'][config['Genome_Version']]['rsem_index'] + '.seq',
        idx_fa = config['STAR_index'][config['Genome_Version']]['rsem_index'] + '.transcripts.fa',
        Transcriptome_bam = '02.mapping/STAR/{sample}/{sample}.Aligned.toTranscriptome.out.bam',
    output:
        genes_result = '03.count/rsem/{sample}.genes.results',
        isoforms_result = '03.count/rsem/{sample}.isoforms.results',
        cnt = '03.count/rsem/{sample}.stat/{sample}.cnt',
        model = '03.count/rsem/{sample}.stat/{sample}.model',
        theta = '03.count/rsem/{sample}.stat/{sample}.theta',
    resources:
        **rule_resource(config, 'high_resource',  skip_queue_on_local=True,logger = logger),
    conda:
        workflow.source_path("../envs/rsem.yaml"),
    message:
        "Running RSEM for BAM : {input.Transcriptome_bam}",
    log:
        "logs/02.mapping/rsem-calculate_{sample}.log",
    benchmark:
        "benchmarks/{sample}_rsem-calculate.txt",
    params:
        sample_name = lambda wildcards: samples[wildcards.sample]["sample_name"],
        rsem_index = config['STAR_index'][config['Genome_Version']]['rsem_index'],
        output_prefix = "03.count/rsem/{sample}",
    threads:
        config['parameter']["threads"]["rsem-calculate"],
    shell:
        """
        rsem-calculate-expression --bam \
                                --no-bam-output \
                                --estimate-rspd \
                                --calc-pme \
                                --seed 12345 \
                                -p {threads} \
                                --paired-end \
                                {input.Transcriptome_bam} \
                                {params.rsem_index} \
                                {params.output_prefix} &>{log}
        """

rule rsem_multiqc:
    """
    Aggregate RSEM quality control metrics using MultiQC.

    This rule collects the .cnt files generated by RSEM (which contain read assignment
    statistics and quality metrics) and generates a comprehensive HTML report using
    MultiQC. The report provides insights into:
    - Read assignment rates across samples
    - Mapping quality distributions
    - Potential technical issues or outliers

    This QC step is essential for validating the quality of quantification results
    before proceeding to downstream differential expression analysis.
    """
    input:
        fastqc_files_r1 = expand("03.count/rsem/{sample}.stat/{sample}.cnt",\
                                  sample=samples.keys()),
    output:
        report = "03.count/multiqc_rsem_report.html",
    conda:
        workflow.source_path("../envs/multiqc.yaml"),
    resources:
        **rule_resource(config, 'low_resource',  skip_queue_on_local=True,logger = logger),
    message:
        "Running MultiQC to aggregate rsem reports",
    params:
        fastqc_reports = "03.count/rsem/",
        report_dir = "03.count/",
        report = "multiqc_rsem_report.html",
        title = "rsem_report",
    log:
        "logs/03.count/rsem_report.log",
    benchmark:
        "benchmarks/rsem_report_benchmark.txt",
    threads:
        config['parameter']['threads']['multiqc'],
    shell:
        """
        multiqc {params.fastqc_reports} \
                --force \
                --outdir {params.report_dir} \
                -i {params.title} \
                -n {params.report} &> {log}
        """

rule merge_rsem:
    """
    Merge individual RSEM results into comprehensive expression matrices.

    This rule aggregates the gene and isoform expression results from all samples
    into three standardized matrix formats:
    - TPM matrix: Transcripts Per Million (normalized for gene length and sequencing depth)
    - Counts matrix: Raw read counts (used for differential expression analysis)
    - FPKM matrix: Fragments Per Kilobase per Million (alternative normalization)

    The merging process uses sample metadata from the sample CSV file to ensure
    proper sample annotation and column ordering. These merged matrices serve as
    the primary input for downstream differential expression and enrichment analyses.
    """
    input:
        genes_result = expand('03.count/rsem/{sample}.genes.results',
                                sample=samples.keys()),
        isoforms_result = expand('03.count/rsem/{sample}.isoforms.results',
                                sample=samples.keys()),
    output:
        tpm = "03.count/merge_rsem_tpm.tsv",
        counts = "03.count/merge_rsem_counts.tsv",
        fpkm = "03.count/merge_rsem_fpkm.tsv",
    resources:
        **rule_resource(config, 'low_resource',  skip_queue_on_local=True,logger = logger),
    conda:
        workflow.source_path("../envs/python3.yaml"),
    message:
        "Running MultiQC to aggregate rsem reports",
    params:
        extension = config["parameter"]['merge_rsem']['extension'],
        input_dir = '03.count/rsem/',
        sample_csv = config['sample_csv'],
        merge_rsem = workflow.source_path(config["parameter"]['merge_rsem']['path']),
    log:
        "logs/03.count/merge_rsem.log",
    benchmark:
        "benchmarks/merge_rsem_benchmark.txt",
    threads: 1
    shell:
        """
        chmod +x {params.merge_rsem} && \
        {params.merge_rsem}  merge-from-dir \
                       --input-dir  {params.input_dir} \
                       --tpm {output.tpm} \
                       --counts {output.counts} \
                       --fpkm {output.fpkm}  \
                       --map {params.sample_csv} \
                       --extension {params.extension} &> {log}
        """

rule ultimate:
    """
    Perform comprehensive quality control and validation of RSEM quantification results.

    This rule runs the 'rsem_ultimate' tool to perform additional quality checks on
    the merged expression matrices. The validation includes:
    - Assessment of quantification accuracy
    - Detection of potential technical artifacts
    - Generation of diagnostic plots and summary statistics

    The output is stored in a dedicated directory containing QC reports and validation
    metrics that help ensure the reliability of downstream analyses. This step is
    particularly important for identifying samples with poor quantification quality
    that might need to be excluded from further analysis.
    """
    input:
        tpm = "03.count/merge_rsem_tpm.tsv",
        counts = "03.count/merge_rsem_counts.tsv",
        fpkm = "03.count/merge_rsem_fpkm.tsv",
    output:
        ultimate = directory("03.count/rsem_ultimate/")
    resources:
        **rule_resource(config, 'low_resource',  skip_queue_on_local=True,logger = logger),
    conda:
        workflow.source_path("../envs/rsem_ultimate.yaml"),
    message:
        "Running rsem_ultimate",
    params:
        extension = workflow.source_path(config["parameter"]['qc_rsem_ultimate']['path']),
    log:
        "logs/03.count/qc_rsem_ultimate.log",
    benchmark:
        "benchmarks/qc_rsem_ultimate_benchmark.txt",
    threads: 1
    shell:
        """
        chmod +x {params.extension} && \
        {params.extension}  --tpm {input.tpm} \
                            --fpkm {input.fpkm} \
                            --counts {input.counts} \
                            --out_dir {output.ultimate} &> {log}
        """