#!/usr/bin/snakemake
# -*- coding: utf-8 -*-
"""
RNAFlow Pipeline - Transcriptome Assembly and Novel Isoform Discovery Module

This module implements a comprehensive transcriptome assembly pipeline using StringTie
for de novo transcript reconstruction and novel isoform discovery from RNA-seq data.

Key Components:
- StringTie_Assembly: Per-sample transcript assembly using reference-guided approach
- StringTie_Merge: Merging individual assemblies into a unified transcript catalog
- GffCompare: Comparison of assembled transcripts against reference annotation
- Filter_Novel_Transcripts: Extraction of novel isoforms and high-confidence transcripts

The pipeline enables both reference-based transcript quantification and discovery of
novel transcripts, alternative splicing events, and gene fusions that may not be
present in the reference annotation. This is particularly valuable for non-model
organisms or studies focused on transcriptome diversity.
"""

rule StringTie_Assembly:
    """
    Perform reference-guided transcript assembly for individual samples using StringTie.

    This rule assembles transcripts from aligned RNA-seq reads using StringTie's
    reference-guided assembly algorithm. By providing a reference GTF/GFF file,
    StringTie can reconstruct known transcripts while also discovering novel isoforms
    and splice variants that may be present in the sample.

    Key parameters:
    - -G: Reference annotation file to guide assembly
    - -l: Sample-specific prefix for transcript IDs
    - -p: Number of threads for parallel processing

    The output is a sample-specific GTF file containing all assembled transcripts
    with their genomic coordinates, exon-intron structures, and expression estimates.
    """
    input:
        bam = "02.mapping/STAR/sort_index/{sample}.sort.bam",
        gtf = config['STAR_index'][config['Genome_Version']]['genome_gff'],
    output:
        gtf = "05.assembly/stringtie/{sample}.gtf"
    resources:
        **rule_resource(config, 'high_resource',  skip_queue_on_local=True,logger = logger),
    conda:
        workflow.source_path("../envs/stringtie.yaml"),
    log:
        "logs/05.assembly/stringtie/{sample}.log",
    benchmark:
        "benchmarks/05.assembly/stringtie/{sample}.txt",
    threads:
        config['parameter']['threads']['stringtie'],
    shell:
        """
        stringtie {input.bam} \
            -G {input.gtf} \
            -o {output.gtf} \
            -p {threads} \
            -l {wildcards.sample} 2> {log}
        """

rule StringTie_Merge:
    """
    Merge individual sample assemblies into a unified, non-redundant transcript catalog.

    This rule combines all sample-specific GTF files generated by StringTie_Assembly
    into a single comprehensive transcript catalog. The merging process resolves
    redundant transcripts across samples and creates a unified set of transcript
    models that represents the complete transcriptome observed across all samples.

    Quality filtering parameters:
    - -m: Minimum transcript length (in bp)
    - -c: Minimum read coverage required for a transcript
    - -F: Minimum FPKM value for transcript inclusion

    The merged GTF serves as the foundation for downstream novel transcript analysis
    and provides a comprehensive view of the expressed transcriptome in the experiment.
    """
    input:
        gtfs = expand("05.assembly/stringtie/{sample}.gtf",
                      sample=samples.keys()),
        ref_gtf = config['STAR_index'][config['Genome_Version']]['genome_gff'],
    output:
        merged_gtf = "05.assembly/stringtie/merged.gtf",
        gtf_list = "05.assembly/stringtie/mergelist.txt",
    resources:
        **rule_resource(config, 'high_resource',  skip_queue_on_local=True,logger = logger),
    conda:
        workflow.source_path("../envs/stringtie.yaml"),
    log:
        "logs/05.assembly/stringtie/merge.log"
    benchmark:
        "benchmarks/05.assembly/stringtie/merge.txt"
    threads:
        config['parameter']['threads']['stringtie'],
    params:
        min_len = config['parameter']['stringtie']['min_length'],
        min_cov = config['parameter']['stringtie']['min_cov'],
        min_fpkm = config['parameter']['stringtie']['min_fpkm'],
    shell:
        """
        (ls {input.gtfs} > {output.gtf_list} && \
        stringtie --merge \
            -p {threads} \
            -G {input.ref_gtf} \
            -o {output.merged_gtf} \
            -m {params.min_len} \
            -c {params.min_cov} \
            -F {params.min_fpkm} \
            {output.gtf_list}) 2> {log}
        """

rule GffCompare:
    """
    Compare assembled transcripts against reference annotation using GffCompare.

    This rule uses GffCompare to systematically compare the merged transcript catalog
    against the reference genome annotation. GffCompare classifies each assembled
    transcript based on its relationship to known reference transcripts using
    standardized class codes:
    - '=': Complete match to reference transcript
    - 'j': Novel isoform (matches reference intron chain but differs in TSS/TES)
    - 'u': Intergenic transcript (completely novel)
    - 'i': Intronic transcript
    - 'x': Exonic overlap with reference on opposite strand
    - And many others...

    The output includes:
    - Annotated GTF with class_code attributes
    - Statistics file summarizing classification results
    - Tracking file mapping assembled to reference transcripts

    This comparison is essential for distinguishing known transcripts from novel
    discoveries and understanding the nature of transcriptome complexity.
    """
    input:
        merged_gtf = "05.assembly/stringtie/merged.gtf",
        ref_gtf = config['STAR_index'][config['Genome_Version']]['genome_gff'],
    output:
        annotated_gtf = "05.assembly/gffcompare/stringtie.annotated.gtf",
        stats = "05.assembly/gffcompare/stringtie.stats",
        tracking = "05.assembly/gffcompare/stringtie.tracking",
    resources:
        **rule_resource(config, 'medium_resource',  skip_queue_on_local=True,logger = logger),
    conda:
        workflow.source_path("../envs/gffcompare.yaml"),
    log:
        "logs/05.assembly/gffcompare/gffcompare.log",
    benchmark:
        "benchmarks/05.assembly/gffcompare/gffcompare.txt",
    params:
        out_prefix = "05.assembly/gffcompare/stringtie",
    threads:
        1
    shell:
        """
        gffcompare -r {input.ref_gtf} \
                   -o {params.out_prefix} \
                   {input.merged_gtf} 2> {log}
        """

rule Filter_Novel_Transcripts:
    """
    Extract high-confidence novel isoforms and reference-matching transcripts.

    This rule filters the GffCompare-annotated GTF to retain only transcripts of
    highest biological interest:
    - Class code '=': Perfect matches to reference transcripts (validation set)
    - Class code 'j': Novel isoforms that share the same intron chain as reference
      transcripts but have different transcription start/end sites

    The filtering logic works in two passes:
    1. First pass: Scan transcript lines to identify valid transcript IDs based on
       class_code criteria
    2. Second pass: Extract all lines (both transcript and exon features) belonging
       to the validated transcript IDs

    Outputs:
    - final_Novel_Isoforms.gtf: Complete GTF containing both reference-matching and
      novel isoform transcripts with all their exons
    - novel_transcripts.gtf: Subset containing only novel isoform transcript lines
      (useful for quick inspection of novel discoveries)

    This filtered set provides a high-confidence catalog of biologically relevant
    transcripts for downstream functional analysis, validation, or database submission.
    """
    input:
        annotated_gtf = "05.assembly/gffcompare/stringtie.annotated.gtf",
    output:
        novel_gtf = "05.assembly/filter/novel_transcripts.gtf",
        final_gtf = "05.assembly/filter/final_Novel_Isoforms.gtf",
    resources:
        **rule_resource(config, 'low_resource',  skip_queue_on_local=True,logger = logger),
    log:
        "logs/05.assembly/filter/filter.log"
    threads: 1
    run:
        valid_codes = set(['=', 'j'])
        valid_transcripts = set()

        with open(input.annotated_gtf, 'r') as f:
            for line in f:
                if line.startswith('#'): continue
                parts = line.strip().split('\t')
                if len(parts) < 9: continue

                if parts[2] == 'transcript':
                    attr_str = parts[8]

                    if 'class_code' in attr_str:
                        try:
                            code_start = attr_str.find('class_code "') + 12
                            code = attr_str[code_start] 

                            if code in valid_codes:
                                tid_start = attr_str.find('transcript_id "') + 15
                                tid_end = attr_str.find('"', tid_start)
                                tid = attr_str[tid_start:tid_end]
                                valid_transcripts.add(tid)
                        except:
                            continue

        with open(input.annotated_gtf, 'r') as fin, \
             open(output.final_gtf, 'w') as f_final, \
             open(output.novel_gtf, 'w') as f_novel:

            for line in fin:
                if line.startswith('#'): continue
                parts = line.strip().split('\t')
                if len(parts) < 9: continue

                attr_str = parts[8]

                if 'transcript_id "' in attr_str:
                    tid_start = attr_str.find('transcript_id "') + 15
                    tid_end = attr_str.find('"', tid_start)
                    tid = attr_str[tid_start:tid_end]

                    if tid in valid_transcripts:
                        f_final.write(line)

                        if parts[2] == 'transcript' and 'class_code "j"' in attr_str:
                            f_novel.write(line)