#!/usr/bin/snakemake
# -*- coding: utf-8 -*-
"""
RNAFlow Pipeline - Comprehensive Quality Control Aggregation Module

This module generates a final, comprehensive MultiQC report that aggregates quality
control metrics from all previous QC steps in the RNA-seq pipeline. This unified report
provides a single dashboard for assessing the overall quality of the entire analysis
workflow.

Key Components:
- merge_qc_report: Aggregates QC results from raw data, trimming, and contamination screening

The comprehensive QC report includes metrics from:
- Raw data quality (FastQC on original reads)
- Adapter trimming and quality filtering (Fastp reports)
- Contamination screening (fastq_screen results)
- Read processing statistics (MD5 validation, file counts)

This final QC aggregation serves as the ultimate quality assurance checkpoint before
proceeding to downstream analysis, ensuring that all samples meet quality standards
and providing a complete audit trail of data processing steps.
"""

import os
# ----- rule ----- #
rule merge_qc_report:
    """
    Generate comprehensive MultiQC report aggregating all quality control metrics.

    This rule creates a final, unified quality control report that combines results
    from all previous QC steps in the pipeline:
    - Raw data quality metrics from FastQC (R1 and R2)
    - Adapter trimming and quality filtering results from Fastp
    - Contamination screening results from fastq_screen
    - Data integrity validation from MD5 checksums

    The comprehensive report provides several key benefits:
    1. **Single Dashboard**: All QC metrics accessible from one HTML report
    2. **Cross-Sample Comparison**: Interactive plots showing quality trends across all samples
    3. **Workflow Validation**: Confirmation that all preprocessing steps completed successfully
    4. **Quality Assurance**: Final checkpoint to ensure data meets analysis standards
    5. **Audit Trail**: Complete documentation of data processing and quality metrics

    The report is generated by scanning the entire '01.qc' directory, which contains
    all QC results from previous steps. MultiQC automatically detects and processes
    compatible report files, creating a cohesive summary that facilitates both
    technical validation and biological interpretation.

    This final QC report is essential for:
    - Validating sample quality before downstream analysis
    - Identifying outlier samples that may need exclusion
    - Documenting data quality for publication or regulatory requirements
    - Providing a comprehensive overview for collaborators or reviewers
    """
    input:
        md5_check = "01.qc/md5_check.tsv",
        fastqc_files_r1 = expand("01.qc/short_read_qc_r1/{sample}_R1_fastqc.zip", sample=samples.keys()),
        fastqc_files_r2 = expand("01.qc/short_read_qc_r2/{sample}_R2_fastqc.zip", sample=samples.keys()),
        r1_trimmed = expand("01.qc/short_read_trim/{sample}.R1.trimed.fq.gz", sample=samples.keys()),
        r2_trimmed = expand("01.qc/short_read_trim/{sample}.R2.trimed.fq.gz", sample=samples.keys()),
        fastp_report = expand("01.qc/short_read_trim/{sample}.trimed.html", sample=samples.keys()),
    output:
        report = '01.qc/multiqc_merge_qc/multiqc_merge_qc_report.html',
    resources:
        **rule_resource(config, 'low_resource',  skip_queue_on_local=True,logger = logger),
    conda:
        workflow.source_path("../envs/multiqc.yaml"),
    params:
        # 建议直接搜索包含所有 QC 结果的根目录
        search_dir = "01.qc",
        out_dir = "01.qc/multiqc_merge_qc",
        report_name = "multiqc_merge_qc_report.html",
        title = "merge qc report",
    log:
        "logs/01.qc/multiqc_merge_qc.log",
    threads:
        config['parameter']['threads']['multiqc'],
    shell:
        """
        mkdir -p {params.out_dir}

        multiqc ./{params.search_dir} \
                --force \
                --outdir {params.out_dir} \
                --title "{params.title}" \
                --filename {params.report_name} \
                &> {log}
        """
# ----- rule ----- #