#!/usr/bin/snakemake
# -*- coding: utf-8 -*-
"""
RNAFlow Pipeline - Final Report Generation Module

This module handles the generation of the final interactive HTML report for the RNA-seq
analysis pipeline. The report is created using a containerized Quarto-based reporting
system that provides a comprehensive, user-friendly interface for exploring all analysis
results.

Key Components:
- generate_docker_json: Creates a project metadata JSON file for the reporting system
- Report: Executes the containerized report generation using Apptainer/Singularity

The reporting system integrates all analysis results into a single, cohesive interface
that includes quality control metrics, differential expression results, functional
enrichment analysis, alternative splicing events, and variant calls. The containerized
approach ensures reproducible report generation across different computing environments.
"""

rule generate_docker_json:
    """
    Generate project metadata JSON configuration for the containerized reporting system.

    This rule creates a comprehensive JSON file that serves as the configuration input
    for the Quarto-based reporting system. The JSON file contains three main sections:

    1. Project Metadata (project_meta):
       - Client information
       - Species and genome version used
       - Pipeline version for reproducibility
       - Analysis date

    2. Project Statistics (stats):
       - Total number of samples analyzed
       - Number of experimental groups/conditions
       - Calculated from the sample sheet CSV file

    3. Input File Paths (input_files):
       - Standardized paths to all analysis results organized by category
       - Uses Docker-compatible path prefixes for container mounting
       - Includes paths to QC reports, expression matrices, DEG results, etc.

    The JSON configuration enables the reporting system to dynamically load and display
    the appropriate analysis results based on what was actually generated by the pipeline,
    providing a flexible and comprehensive reporting solution.
    """
    input:
        manifest_json = os.path.join(config['data_deliver'],'report_data','delivery_manifest.json'),
        manifest_md5 = os.path.join(config['data_deliver'],'report_data','delivery_manifest.md5'),
        manifest_log = os.path.join(config['data_deliver'],'report_data','delivery_details.log'),
        sample_sheet = config['sample_csv'],
    output:
        json_file = os.path.join(config['data_deliver'], "report_data/project_summary.json")
    resources:
        **rule_resource(config, 'low_resource',  skip_queue_on_local=True,logger = logger),
    conda:
        workflow.source_path("../envs/py3.12.yaml"),
    params:
        client = config["client"],
        species = config["species"],
        Genome_Version = config["Genome_Version"],
        pipeline_version = config["pipeline_version"],
        docker_prefix = "/data"
    run:
        import pandas as pd
        import datetime
        import json
        import os

        df = pd.read_csv(input.sample_sheet)
        calculated_sample_count = len(df)
        calculated_group_count = df['group'].nunique()
        analysis_date = datetime.date.today().strftime("%Y-%m-%d")
        project_meta = {
            "client": params.client,
            "species": params.species,
            "genome_version": params.Genome_Version,
            "pipeline_version": params.pipeline_version,
            "analysis_date": analysis_date
        }
        stats = {
            "total_samples": int(calculated_sample_count),
            "group_count": int(calculated_group_count)
        }
        input_files = {
            "data_dir": f"{params.docker_prefix}/index/",
            "qc_file": f"{params.docker_prefix}/index/multiqc_qc_general_stats.txt",
            "mapping_file": f"{params.docker_prefix}/index/multiqc_mapping_general_stats.txt",
            "tpm_file": f"{params.docker_prefix}/index/merge_rsem_tpm.tsv",
            "sample_file": f"{params.docker_prefix}/index/sample.csv",
            "fastp_report_dir": f"{params.docker_prefix}/fastp_trim_report/multiqc_short_read_trim_report_data",
            "fastp_stats_file": f"{params.docker_prefix}/fastp_trim_report/multiqc_general_stats.txt",
            "fastq_screen_r1_dir": f"{params.docker_prefix}/fastq_screen_report/fastq_screen_multiqc_r1/multiqc_r1_fastq_screen_report_data",
            "fastq_screen_r2_dir": f"{params.docker_prefix}/fastq_screen_report/fastq_screen_multiqc_r2/multiqc_r2_fastq_screen_report_data",
            "qualimap_dir": f"{params.docker_prefix}/QualiMap/multiqc_data/",
            "contrasts_file": f"{params.docker_prefix}/index/contrasts.csv",
            "deg_dir": f"{params.docker_prefix}/res/DEG",
            "enrichment_dir": f"{params.docker_prefix}/res/Enrichments"
        }
        final_data = {
            "project_meta": project_meta,
            "stats": stats,
            "input_files": input_files
        }
        os.makedirs(os.path.dirname(output.json_file), exist_ok=True)
        with open(output.json_file, 'w', encoding='utf-8') as f:
            json.dump(final_data, f, indent=2, ensure_ascii=False)
rule Report:
    """
    Generate the final interactive HTML report using a containerized Quarto application.

    This rule executes the final report generation by running a Docker container
    directly. The containerized approach ensures consistent report generation
    across different computing environments and eliminates dependency conflicts.

    Key features of the reporting system:
    - Interactive HTML interface with dynamic data visualization
    - Comprehensive integration of all analysis modules (QC, DEG, enrichment, AS, variants)
    - Responsive design suitable for both desktop and mobile viewing
    - Export capabilities for figures and tables
    - Reproducible report generation using container technology

    Container execution details:
    - Uses docker run with --rm flag to automatically clean up the container after execution
    - Mounts the report data directory to /data inside the container using -v
    - Mounts the project summary JSON configuration to /app/project_summary.json
    - Mounts the output report directory to /workspace/ for result storage
    - Uses the specified local Docker image directly

    The final output is a self-contained HTML report with embedded JavaScript
    visualizations that can be easily shared with collaborators or uploaded to
    web servers for remote access.
    """
    input:
        DataDeliver(config),
        json_file = os.path.join(config['data_deliver'], "report_data/project_summary.json"),
        manifest_json = os.path.join(config['data_deliver'],'report_data','delivery_manifest.json'),
        manifest_md5 = os.path.join(config['data_deliver'],'report_data','delivery_manifest.md5'),
        manifest_log = os.path.join(config['data_deliver'],'report_data','delivery_details.log'),
    output:
        Report_html =  os.path.join(config['data_deliver'], "Analysis_Report/index.html")
    resources:
        **rule_resource(config, 'high_resource',  skip_queue_on_local=True,logger = logger),
    conda:
        workflow.source_path("../envs/py3.12.yaml"),
    params:
        data_dir = os.path.join(config['data_deliver'],'report_data','data'),
        Report_dir = os.path.join(config['data_deliver'], "Analysis_Report"),
        docker_version = config['parameter']['Report']['docker_version'],
    log:
        "logs/Report.log",
    benchmark:
        "benchmark/Report.txt",
    threads:
        config['parameter']['threads']['Report'],
    shell:
        """
        (
        IMAGE_NAME={params.docker_version}

        # 1. CHECK IF DOCKER IMAGE EXISTS
        if [ -z "$(docker images -q $IMAGE_NAME)" ]; then
            echo "错误: 镜像 $IMAGE_NAME 不存在！请先拉取或构建该镜像。"
            exit 1
        else
            echo "找到镜像: $IMAGE_NAME"
        fi

        # 2. RUN DOCKER CONTAINER WITH CORRECT MOUNTING AND USER PERMISSIO
        mkdir -p {params.Report_dir} 
        docker run --rm --user $(id -u):$(id -g) \
                   -v {params.data_dir}:/data:rw \
                   -v {params.Report_dir}:/workspace:rw \
                   -v {input.json_file}:/app/project_summary.json:rw \
                   {params.docker_version} 
        ) &> {log}
        """